import { initializeApp } from 'firebase/app';
import { getFirestore, writeBatch, doc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const clusters = [
  { id: 'identity', num: '01', title: 'Identity & Addressability', desc: 'How users get recognized across sites, devices, and sessions. The foundation of targeting, frequency capping, and measurement.' },
  { id: 'players', num: '02', title: 'The Players', desc: 'The companies, categories, and roles that make up the adtech ecosystem.' },
  { id: 'data', num: '03', title: 'Data & Activation', desc: 'How customer data flows from CRMs into the ad ecosystem and back as measurement.' },
  { id: 'privacy', num: '04', title: 'Privacy & Regulation', desc: 'The rules and frameworks reshaping how identity and data work in advertising.' },
  { id: 'auction', num: '05', title: 'Auction Mechanics', desc: 'How real-time bidding works under the hood. Every impression is a 100ms auction.' },
  { id: 'channels', num: '06', title: 'Channels & Inventory', desc: 'The surfaces where ads actually appear. Each channel has its own identity and measurement dynamics.' },
  { id: 'adquality', num: '07', title: 'Ad Quality & Supply Integrity', desc: 'Not all impressions are real. Not all paths to publishers are direct. This cluster covers the systems that keep the ecosystem honest.' },
  { id: 'creative', num: '08', title: 'Creative Formats & Standards', desc: 'How ads are packaged, described, and measured. Each format has its own OpenRTB object and delivery spec.' },
  { id: 'measurement', num: '09', title: 'Measurement & Tracking', desc: 'How an ad click becomes a data point on a dashboard. The most fragile part of the entire chain.' },
  { id: 'pubmonetization', num: '10', title: 'Publisher Monetization', desc: 'How publishers maximize revenue from their inventory. The supply-side operational layer.' },
  { id: 'performance', num: '11', title: 'Performance Marketing', desc: 'If it performs, you pay. The demand-side operational layer — how advertisers run, optimize, and scale campaigns.' },
  { id: 'commercial', num: '12', title: 'Commercial Language', desc: 'Vocabulary used by senior partnerships, BD, and sales people. Learn to use these naturally.' },
];

const terms = [
  // 01 Identity
  { id: 'identity-resolution', clusterId: 'identity', name: 'Identity Resolution', def: 'The practice of recognizing the same user across different sites, devices, apps, and sessions. The foundation that makes targeting, frequency capping, and measurement possible.', related: ['rampid','id5','uid2','first-party-data','third-party-cookies','measurement','cookie-sync','consent-string'] },
  { id: 'uid', clusterId: 'identity', name: 'UID (Unique Identifier)', def: 'The actual value stored inside a cookie — an alphanumeric string like abc123xyz. Not your name or email. Used by DSPs and SSPs to recognize you in auctions. Without a UID, a DSP is bidding on a ghost.', related: ['identity-resolution','cookie-sync','third-party-cookies','bid-request'] },
  { id: 'rampid', clusterId: 'identity', name: 'RampID', def: "LiveRamp's identity product. Connects first-party CRM data to the programmatic ecosystem across DSPs, SSPs, CTV, and walled gardens. The enterprise standard for brands with large customer databases.", related: ['liveramp','identity-resolution','onboarding','activation','seller-defined-audiences'] },
  { id: 'id5', clusterId: 'identity', name: 'ID5 ID', def: 'European, independent identity provider. Privacy-first alternative to legacy IDs. Operates without requiring user login — uses probabilistic matching. Partnered with Unity to extend into mobile gaming.', related: ['identity-resolution','privacy-by-design','mobile-gaming','idfa'] },
  { id: 'uid2', clusterId: 'identity', name: 'UID2', def: 'Unified ID 2.0 — open-source identity standard by The Trade Desk, now managed by Prebid.org. Based on hashed and encrypted email. Requires user login on the publisher side to work.', related: ['identity-resolution','first-party-data','third-party-cookies','the-trade-desk','seller-defined-audiences'] },
  { id: 'idfa', clusterId: 'identity', name: 'IDFA', def: "Apple's mobile device identifier. Made opt-in by ATT in 2021. Most iOS users decline — effectively collapsing addressable iOS inventory for advertisers who relied on it.", related: ['att','mobile-in-app','legacy-ids','gaid'] },
  { id: 'gaid', clusterId: 'identity', name: 'GAID', def: "Google Advertising ID — Android's equivalent of IDFA. Still active but Google is restricting it via Android Privacy Sandbox. The next legacy ID expected to fade.", related: ['idfa','legacy-ids','mobile-in-app'] },
  { id: 'third-party-cookies', clusterId: 'identity', name: '3rd-Party Cookies', def: 'Cookies set by domains other than the one a user is visiting. Used for cross-site tracking for ~20 years. Already blocked in Safari and Firefox. Chrome moved to user-choice in 2024.', related: ['identity-resolution','first-party-data','legacy-ids','privacy-by-design','cookie-sync'] },
  { id: 'legacy-ids', clusterId: 'identity', name: 'Legacy IDs', def: 'The dying identifiers: third-party cookies, IDFA, GAID. The category that RampID, ID5, and UID2 are designed to replace.', related: ['third-party-cookies','idfa','gaid','identity-resolution'] },
  { id: 'contextual-targeting', clusterId: 'identity', name: 'Contextual Targeting', def: "Targeting based on the page's content and semantics rather than who the user is. In 2026, AI reads entire pages — understanding sentiment, topic, and intent. Fully privacy-safe: no user ID required.", related: ['identity-resolution','privacy-by-design','third-party-cookies','brand-safety'] },
  { id: 'seller-defined-audiences', clusterId: 'identity', name: 'Seller-Defined Audiences', def: 'Publisher-built audience segments using their own first-party data, shared with buyers via IAB taxonomy. No PII exchanged. Publishers signal "this is a travel enthusiast" without revealing who the person is.', related: ['first-party-data','rampid','uid2','publisher-ad-server'] },
  { id: 'consent-string', clusterId: 'identity', name: 'Consent String', def: "An encoded (base64) signal carrying a user's consent choices through the entire programmatic chain. Travels inside the bid request in the user.consent field. SSPs and DSPs read it to decide whether they can process data.", related: ['tcf','gdpr','cmp','bid-request','openrtb'] },
  { id: 'cookie-sync', clusterId: 'identity', name: 'Cookie Sync', def: "The process where two platforms (e.g., SSP and DSP) exchange their internal user IDs for the same person using redirects and pixels. Works around the browser's same-origin policy. Enables coordinated bidding and frequency capping.", related: ['uid','identity-resolution','third-party-cookies','bid-request','ssp','dsp'] },

  // 02 Players
  { id: 'dsp', clusterId: 'players', name: 'DSP', def: 'Demand-Side Platform. Software advertisers and agencies use to buy impressions across many exchanges from one interface. Evaluates each bid request and decides whether to bid, how much, and with which creative. Examples: The Trade Desk, DV360, Amazon DSP, LoopMe.', related: ['ssp','ad-exchange','openrtb','bid-request','brands','smart-bidding'] },
  { id: 'ssp', clusterId: 'players', name: 'SSP', def: 'Supply-Side Platform. Software publishers use to sell their inventory programmatically. Packages each impression as a bid request and sends it to exchanges and DSPs. Goal: maximize yield. Examples: Magnite, PubMatic, Index Exchange.', related: ['dsp','ad-exchange','publishers','header-bidding','floor-price','cookie-sync'] },
  { id: 'ad-exchange', clusterId: 'players', name: 'Ad Exchange', def: 'The marketplace where DSPs and SSPs meet. Runs real-time auctions for each impression. LoopMe operates as one. Receives the bid request from the SSP and distributes it to DSPs.', related: ['dsp','ssp','openrtb','bidstream'] },
  { id: 'publisher-ad-server', clusterId: 'players', name: 'Publisher Ad Server', def: "The brain of a publisher's monetization. Decides what actually renders in each slot — prioritizing direct deals, managing header bidding logic, serving house ads when nothing fills. GAM is the dominant example.", related: ['gam','publishers','header-bidding','ssp','ad-unit','line-item'] },
  { id: 'advertiser-ad-server', clusterId: 'players', name: 'Advertiser Ad Server', def: 'Third-party ad server (CM360, Flashtalking) used by agencies to centralize creative hosting. Host once, send tags to all DSPs. Also owns the authoritative impression and click count across all buys.', related: ['dsp','brands','click-id','impression-pixel'] },
  { id: 'big-4', clusterId: 'players', name: 'Big 4 (Agencies)', def: 'WPP, Omnicom, IPG, and Publicis. They control enormous media budgets globally and influence which DSPs, SSPs, and identity solutions get adopted at scale.', related: ['publicis','liveramp','brands'] },
  { id: 'publicis', clusterId: 'players', name: 'Publicis Groupe', def: 'French agency holding company, one of the Big 4. Acquired LiveRamp in May 2026 for $2.2B — a 29.8% premium. Signals the agency world moving to control identity infrastructure directly.', related: ['big-4','liveramp','rampid','data-co-creation'] },
  { id: 'liveramp', clusterId: 'players', name: 'LiveRamp', def: 'Identity and data collaboration company. Runs RampID. Connects 25,000+ publishers and 500+ tech partners. Acquired by Publicis in May 2026, ending its status as a neutral infrastructure provider.', related: ['rampid','publicis','identity-resolution','clean-rooms'] },
  { id: 'the-trade-desk', clusterId: 'players', name: 'The Trade Desk', def: 'Largest independent DSP. Pioneered UID2. A key benchmark for demand-side strategy in the industry.', related: ['dsp','uid2'] },
  { id: 'mmp', clusterId: 'players', name: 'MMP', def: 'Mobile Measurement Partner — AppsFlyer, Adjust. The attribution referee for mobile campaigns. When Meta, the DSP, and a network all claim credit for an install, the MMP holds the authoritative answer based on the click ID it matched.', related: ['click-id','attribution-window','idfa','gaid','mobile-in-app'] },
  { id: 'publishers', clusterId: 'players', name: 'Publishers', def: 'Companies that own websites, apps, or content where ads appear. They sell inventory through SSPs or directly via publisher ad servers.', related: ['ssp','header-bidding','gam','ad-unit','brands'] },
  { id: 'brands', clusterId: 'players', name: 'Brands / Advertisers', def: 'The companies that pay to run ads. Buy media through agencies or directly through DSPs. Own the first-party data that powers the best targeting.', related: ['big-4','dsp','first-party-data'] },

  // 03 Data
  { id: 'first-party-data', clusterId: 'data', name: '1st-Party Data', def: 'Data a company collects directly from its own customers — purchases, signups, app usage, login data. The most valuable kind: owned, accurate, consented. Increasingly the only reliable targeting signal.', related: ['third-party-cookies','onboarding','activation','crm','seller-defined-audiences','clean-rooms'] },
  { id: 'crm', clusterId: 'data', name: 'CRM Data', def: "Customer Relationship Management data — the customer records a brand holds: emails, purchase history, loyalty status. The raw material that gets onboarded into the ad ecosystem via LiveRamp or similar.", related: ['first-party-data','onboarding','activation'] },
  { id: 'onboarding', clusterId: 'data', name: 'Data Onboarding', def: "Taking offline data (CRM lists, loyalty programs, store purchase records) and making it usable for digital ad targeting. LiveRamp's historical core business: hashing emails and matching them to browser IDs.", related: ['rampid','first-party-data','crm','activation'] },
  { id: 'activation', clusterId: 'data', name: 'Audience Activation', def: 'Taking onboarded or modeled data and actually using it to target ads across platforms. The action that follows onboarding — pushing segments into DSPs to bid on specific users.', related: ['onboarding','first-party-data','rampid','measurement','seller-defined-audiences'] },
  { id: 'clean-rooms', clusterId: 'data', name: 'Data Clean Rooms', def: "Secure environments (Snowflake, Amazon Marketing Cloud, InfoSum) where two parties match their data without either seeing the other's raw records. A brand and publisher can find shared users without sharing PII.", related: ['data-co-creation','privacy-by-design','liveramp','first-party-data'] },
  { id: 'data-co-creation', clusterId: 'data', name: 'Data Co-Creation', def: 'Combining first-party data from multiple partners inside clean rooms to build proprietary new audience segments. Buzzword popularized by Publicis after the LiveRamp acquisition.', related: ['clean-rooms','first-party-data','publicis'] },
  { id: 'measurement', clusterId: 'data', name: 'Measurement & Attribution', def: 'Proving that an ad actually drove a desired outcome. Identity is the foundation — without a stable user ID, you cannot connect an impression to a conversion.', related: ['identity-resolution','activation','rampid','click-id','conversion-pixel','mmp'] },
  { id: 'product-feed', clusterId: 'data', name: 'Product Feed', def: 'A structured file (XML, CSV, or JSON) containing every product ID, title, price, image URL, and availability. The source of truth that powers dynamic retargeting. Without a healthy feed, DCO campaigns break entirely.', related: ['dco','retargeting-segments','dsp'] },

  // 04 Privacy
  { id: 'gdpr', clusterId: 'privacy', name: 'GDPR', def: 'General Data Protection Regulation — EU privacy law since 2018. Operates on opt-in: you cannot track a user unless they explicitly say yes. Requires consent for almost all data processing in digital advertising.', related: ['ccpa','privacy-by-design','cmp','tcf','consent-string'] },
  { id: 'ccpa', clusterId: 'privacy', name: 'CCPA / CPRA', def: "California Consumer Privacy Act. Operates on opt-out: tracking is allowed by default, but users must be given a 'Do Not Sell My Personal Information' option. The US's most significant state-level privacy law.", related: ['gdpr','privacy-by-design','consent-string'] },
  { id: 'att', clusterId: 'privacy', name: 'ATT (Apple)', def: "App Tracking Transparency — Apple's 2021 framework making IDFA opt-in. Most iOS users decline. Collapsed addressable iOS inventory and forced the entire mobile attribution industry to rebuild.", related: ['idfa','mobile-in-app','legacy-ids','mmp'] },
  { id: 'privacy-by-design', clusterId: 'privacy', name: 'Privacy-by-Design', def: 'GDPR principle requiring privacy to be built into systems from the start, not added as a patch. Used as a positioning claim by identity providers like ID5 and contextual targeting vendors.', related: ['gdpr','id5','clean-rooms','contextual-targeting'] },
  { id: 'cmp', clusterId: 'privacy', name: 'CMP', def: "Consent Management Platform — the tool behind every cookie banner (OneTrust, Sourcepoint, Quantcast). Its real job isn't showing the banner — it's generating a consent string that travels with every subsequent ad call.", related: ['gdpr','consent-string','tcf'] },
  { id: 'tcf', clusterId: 'privacy', name: 'TCF 2.2', def: 'Transparency and Consent Framework — IAB standard defining how EU user consent is encoded and transmitted through the programmatic chain. Specifies which purposes a user agreed to and which vendors can act on that consent.', related: ['gdpr','consent-string','cmp','openrtb'] },

  // 05 Auction
  { id: 'openrtb', clusterId: 'auction', name: 'OpenRTB', def: 'The open protocol (IAB standard) that defines how bid requests and responses flow between SSPs and DSPs. The common language of programmatic advertising. Current version: 2.6.', related: ['bid-request','bid-response','dsp','ssp','bidstream','consent-string'] },
  { id: 'bid-request', clusterId: 'auction', name: 'Bid Request', def: 'The JSON message an SSP sends to DSPs when an impression is available. Contains: user/device signals, page/app context, ad slot specs, floor price, consent string, and identity signals. DSPs have ~100ms to respond.', related: ['openrtb','bid-response','identity-resolution','uid','floor-price','consent-string'] },
  { id: 'bid-response', clusterId: 'auction', name: 'Bid Response', def: "The DSP's answer to a bid request. Contains: a bid price, creative markup, and tracking URLs. A no-bid response is also valid — the DSP simply passes.", related: ['openrtb','bid-request','ecpm','advertiser-ad-server'] },
  { id: 'bidstream', clusterId: 'auction', name: 'Bidstream', def: 'The continuous flow of bid requests and responses across the ecosystem. Analyzing bidstream data is core TAM work — bid response rate, win rate, and traffic quality all live here.', related: ['openrtb','bid-request','win-rate','ad-exchange'] },
  { id: 'ecpm', clusterId: 'auction', name: 'eCPM', def: 'Effective Cost Per Mille — blended publisher revenue per 1,000 impressions across all demand sources. Formula: (Total Revenue ÷ Impressions) × 1,000. The primary publisher performance metric.', related: ['rcpm','win-rate','fill-rate','floor-price','header-bidding'] },
  { id: 'win-rate', clusterId: 'auction', name: 'Win Rate', def: 'Share of submitted bids that a DSP wins. Low win rate often signals a floor price mismatch or targeting configuration issue.', related: ['ecpm','bid-response','fill-rate','floor-price'] },
  { id: 'fill-rate', clusterId: 'auction', name: 'Fill Rate', def: 'Share of ad opportunities that get filled with an ad. Formula: (Filled impressions ÷ Ad requests) × 100%. Low fill rate = wasted inventory — floor set too high or insufficient demand.', related: ['ecpm','win-rate','floor-price','ad-refresh'] },
  { id: 'floor-price', clusterId: 'auction', name: 'Floor Price', def: 'The minimum bid a publisher will accept for an impression. Set in the SSP and passed in the bid request. Floor strategy directly affects fill rate, win rate, eCPM, and revenue.', related: ['ecpm','fill-rate','floor-strategy','ssp'] },
  { id: 'qps', clusterId: 'auction', name: 'QPS', def: 'Queries Per Second — the rate of bid requests flowing through a system. Traffic shaping reduces QPS to only high-value opportunities, improving efficiency for both SSPs and DSPs.', related: ['openrtb','bidstream'] },
  { id: 'pmp', clusterId: 'auction', name: 'PMP', def: 'Private Marketplace — invite-only programmatic auction between specific publishers and specific buyers. Higher-quality inventory, more transparency, better eCPMs than open auction.', related: ['pg','openrtb','header-bidding','floor-price'] },
  { id: 'pg', clusterId: 'auction', name: 'Programmatic Guaranteed', def: 'Pre-negotiated direct deal executed programmatically. Fixed price, guaranteed volume — the digital equivalent of a traditional IO but with targeting flexibility and automated delivery.', related: ['pmp','gam','line-item'] },
  { id: 'header-bidding', clusterId: 'auction', name: 'Header Bidding', def: 'Publishers offer inventory to multiple SSPs simultaneously before calling the ad server. All SSPs respond in parallel; the highest bid enters GAM to compete with direct deals. Replaced the waterfall model and increased publisher revenue 20–50%.', related: ['ssp','publishers','ecpm','prebid-js','gam','waterfall'] },
  { id: 'waterfall', clusterId: 'auction', name: 'Waterfall', def: "The legacy sequential auction model — the publisher's ad server calls demand partners one by one in priority order. The first to fill wins, regardless of whether a later partner would have paid more. Largely replaced by header bidding.", related: ['header-bidding','gam','publisher-ad-server'] },

  // 06 Channels
  { id: 'display', clusterId: 'channels', name: 'Display / Web', def: 'Banner and rich-media ads on websites. The original programmatic channel. Most affected by third-party cookie deprecation. Standard IAB sizes: MREC (300×250), Leaderboard (728×90), Halfpage (300×600).', related: ['third-party-cookies','header-bidding','publishers','mrec'] },
  { id: 'mobile-in-app', clusterId: 'channels', name: 'Mobile In-App', def: "Ads inside mobile apps. Uses IDFA and GAID instead of cookies. Most affected by ATT. LoopMe's core territory. Governed by MRAID for interactive banners and VAST for video.", related: ['idfa','gaid','att','mobile-gaming','vast','om-sdk'] },
  { id: 'mobile-gaming', clusterId: 'channels', name: 'Mobile Gaming', def: '2.5B+ players globally. High engagement, hard to monetize post-IDFA without alternative IDs. Unity is the dominant ad platform. ID5 has moved into this channel.', related: ['mobile-in-app','id5','idfa'] },
  { id: 'ctv', clusterId: 'channels', name: 'CTV', def: 'Connected TV — streaming services, smart TVs, Roku, Fire TV. Fastest-growing premium channel. No cookies, no IDFA — relies on device IDs and IP-based identity. High CPMs, brand-safe inventory.', related: ['identity-resolution','activation','vast'] },
  { id: 'video', clusterId: 'channels', name: 'Video (Pre/Mid/Post-Roll)', def: 'Video ads served before, during, or after video content. Governed by VAST for delivery and VPAID for interactivity. Highest CPMs in programmatic. Viewability standard: 50% of pixels visible for ≥2 seconds.', related: ['vast','vpaid','viewability','om-sdk','ctv','mobile-in-app'] },
  { id: 'native', clusterId: 'channels', name: 'Native Ads', def: 'Ads that match the form and function of surrounding content — in-feed articles, recommendation widgets (Taboola, Outbrain), sponsored product listings. Served as modular assets via the OpenRTB native spec.', related: ['openrtb','dsp','contextual-targeting','dco'] },

  // 07 Ad Quality
  { id: 'ivt', clusterId: 'adquality', name: 'IVT (Invalid Traffic)', def: 'Any clicks, impressions, or conversions not generated by real, engaged humans. Split into GIVT (detectable) and SIVT (sophisticated). Drains ad budgets and corrupts performance data.', related: ['givt','sivt','brand-safety','spo','ads-txt','viewability'] },
  { id: 'givt', clusterId: 'adquality', name: 'GIVT', def: 'General Invalid Traffic — the detectable kind: known bots (Googlebot, Bingbot), data center IPs, fake user agents, automated pre-fetching. Usually filtered pre-bid by DSPs and SSPs using standard blocklists.', related: ['ivt','sivt','spo'] },
  { id: 'sivt', clusterId: 'adquality', name: 'SIVT', def: 'Sophisticated Invalid Traffic — the hard-to-catch kind: click farms, ad stacking, pixel stuffing, domain spoofing, SDK simulation. Designed to mimic human behavior. Requires specialized detection (HUMAN, Pixalate).', related: ['ivt','givt','ad-stacking','pixel-stuffing','spo'] },
  { id: 'ad-stacking', clusterId: 'adquality', name: 'Ad Stacking', def: 'Layering multiple ads invisibly in the same slot. Only the top is seen, but all are counted as delivered impressions. A form of SIVT that inflates publisher revenue fraudulently.', related: ['sivt','viewability','impression-pixel'] },
  { id: 'pixel-stuffing', clusterId: 'adquality', name: 'Pixel Stuffing', def: 'Placing ads in 1×1 pixel slots — technically delivered, never actually seen. Inflates impression counts while providing zero real exposure.', related: ['sivt','viewability','impression-pixel'] },
  { id: 'brand-safety', clusterId: 'adquality', name: 'Brand Safety', def: "Ensuring ads don't appear next to harmful content — hate speech, violence, extremism. Enforced through blocklists, IAB content categorization, and verification tools (DoubleVerify, IAS).", related: ['ivt','contextual-targeting','spo','ads-txt'] },
  { id: 'spo', clusterId: 'adquality', name: 'SPO', def: 'Supply Path Optimization — finding the shortest, most transparent, most cost-efficient path from DSP to publisher. Cuts out unnecessary resellers, reduces the adtech tax, improves inventory quality.', related: ['ads-txt','sellers-json','schain','ivt','dsp','ssp'] },
  { id: 'ads-txt', clusterId: 'adquality', name: 'Ads.txt', def: "A text file publishers place on their domain listing exactly which SSPs and exchanges are authorized to sell their inventory. DSPs validate against it to avoid buying spoofed supply.", related: ['spo','schain','sellers-json','publishers'] },
  { id: 'sellers-json', clusterId: 'adquality', name: 'Sellers.json', def: "An SSP's public JSON file listing every publisher it represents and whether they're a direct seller or reseller. Allows buyers to trace who actually gets paid.", related: ['spo','ads-txt','schain'] },
  { id: 'schain', clusterId: 'adquality', name: 'SupplyChain Object', def: 'An OpenRTB extension recording every node (SSP, exchange, reseller) that touched a bid request. The passport of a bid request — proves the supply chain has no hidden intermediaries.', related: ['spo','ads-txt','sellers-json','openrtb','bid-request'] },

  // 08 Creative
  { id: 'vast', clusterId: 'creative', name: 'VAST', def: "Video Ad Serving Template — IAB's XML standard for video ad delivery. Defines what video creative to play, how long, whether skippable, and which URLs to fire for impression/click/completion tracking.", related: ['vpaid','video','om-sdk','bid-response','vast-wrapper'] },
  { id: 'vast-wrapper', clusterId: 'creative', name: 'VAST Wrapper', def: 'A VAST response that points to another VAST URL instead of a direct creative. Used for third-party ad serving and measurement. Multiple wrappers create a VAST chain — each adding latency. Too many = video fails to load.', related: ['vast','advertiser-ad-server','impression-pixel'] },
  { id: 'vpaid', clusterId: 'creative', name: 'VPAID', def: 'Video Player Ad Interface Definition — interactive extension of VAST. Allows ad creative to communicate with the video player: reporting hover events, showing overlays, running mini-interactions.', related: ['vast','video','mobile-in-app'] },
  { id: 'mrec', clusterId: 'creative', name: 'MREC (300×250)', def: 'Medium Rectangle — the most widely used banner format in programmatic. Works in sidebars, in-content, and mobile. The default format for many display campaigns.', related: ['display','banner-object','header-bidding'] },
  { id: 'banner-object', clusterId: 'creative', name: 'Banner Object', def: 'The OpenRTB object inside the bid request describing a display ad slot — specifying dimensions, supported formats, position on page, and allowed creative attributes.', related: ['openrtb','bid-request','mrec','display'] },
  { id: 'viewability', clusterId: 'creative', name: 'Viewability', def: 'IAB standard: a display ad is viewable when 50% of pixels are visible for at least 1 second. Video: 50% visible for at least 2 seconds. Directly affects eCPM — advertisers pay more for high-viewability inventory.', related: ['om-sdk','ad-refresh','ivt','ecpm','lazy-loading','impression-pixel'] },
  { id: 'om-sdk', clusterId: 'creative', name: 'OM SDK', def: "IAB's Open Measurement SDK — a single unified SDK replacing the fragmented per-vendor measurement landscape. Before it, a publisher's app might carry 5 separate SDKs just to prove viewability.", related: ['viewability','mobile-in-app','brand-safety'] },
  { id: 'dco', clusterId: 'creative', name: 'DCO', def: 'Dynamic Creative Optimization — assembling personalized ad creatives in real time from a product feed. The DSP wins an auction, identifies the user, pulls the relevant product data, and injects it into a pre-designed template.', related: ['product-feed','retargeting-segments','dsp','native'] },

  // 09 Measurement
  { id: 'impression-pixel', clusterId: 'measurement', name: 'Impression Pixel', def: 'A tiny URL request fired the moment an ad renders in a browser. How platforms record delivery. Ad stacking and pixel stuffing exploit this: they fire the pixel without a viewable impression.', related: ['viewability','ad-stacking','pixel-stuffing','conversion-pixel','advertiser-ad-server'] },
  { id: 'click-id', clusterId: 'measurement', name: 'Click ID', def: 'A unique alphanumeric string assigned to each individual ad click. Created during the redirect checkpoint. The fingerprint connecting this specific click to any future conversion. No two clicks share the same ID.', related: ['utm','conversion-pixel','gtm','mmp','attribution-window'] },
  { id: 'utm', clusterId: 'measurement', name: 'UTM Parameters', def: 'URL labels (utm_source, utm_medium, utm_campaign) for analytics tools. Group-level reporting — if 10,000 people click the same link, they all carry identical UTMs. Useful for channel analysis, useless for individual attribution.', related: ['click-id','gtm','measurement'] },
  { id: 'conversion-pixel', clusterId: 'measurement', name: 'Conversion Pixel', def: "A signal fired from the confirmation page (purchase, signup, install) back to the ad platform. Contains the click ID matched to this conversion and the conversion value. How the platform closes the loop from impression to outcome.", related: ['click-id','gtm','measurement','mmp','impression-pixel'] },
  { id: 'gtm', clusterId: 'measurement', name: 'GTM', def: "Google Tag Manager — the container managing all tracking tags on a site. On landing page: reads click ID from URL and stores it in a cookie. On conversion page: fires the conversion pixel with the stored click ID.", related: ['click-id','conversion-pixel','utm','measurement'] },
  { id: 'attribution-window', clusterId: 'measurement', name: 'Attribution Window', def: "The time period in which a click or view can be credited with a conversion. Typical: 7-day click, 1-day view. Platform choice of window significantly affects reported ROAS.", related: ['click-id','mmp','last-click-attribution','view-through'] },
  { id: 'view-through', clusterId: 'measurement', name: 'View-Through Attribution', def: 'Crediting a conversion to an ad that was seen but not clicked. If someone sees your display ad Monday and converts Thursday, view-through gives that ad partial credit. Easy to abuse — most sophisticated advertisers apply skepticism.', related: ['attribution-window','measurement','impression-pixel','last-click-attribution'] },
  { id: 'last-click-attribution', clusterId: 'measurement', name: 'Last-Click Attribution', def: 'Giving 100% conversion credit to the final touchpoint before the purchase. Simple, widely used, and distorting — it systematically over-credits retargeting and brand search while ignoring the full funnel.', related: ['attribution-window','data-driven-attribution','measurement','view-through'] },
  { id: 'data-driven-attribution', clusterId: 'measurement', name: 'Data-Driven Attribution', def: 'ML model distributing conversion credit across all touchpoints based on actual contribution. If users who saw both TikTok and Google ads convert 3× more than those who saw only Google, TikTok gets proportional credit.', related: ['last-click-attribution','measurement','smart-bidding'] },

  // 10 Publisher Monetization
  { id: 'gam', clusterId: 'pubmonetization', name: 'GAM', def: "Google Ad Manager — the dominant enterprise publisher ad server. Manages direct deals, programmatic auctions, house ads, and yield optimization. Think of it as the stadium's ticketing system, security gate, and scoreboard all in one.", related: ['publisher-ad-server','ad-unit','line-item','gpt','header-bidding','prebid-js'] },
  { id: 'ad-unit', clusterId: 'pubmonetization', name: 'Ad Unit', def: "A defined ad slot on a site or app — the real estate a publisher monetizes. In GAM, named hierarchically (Brand > Section > Page_Type > Position) for clean reporting. Each unit gets a GPT tag that calls GAM on every page load.", related: ['gam','gpt','publishers','line-item'] },
  { id: 'line-item', clusterId: 'pubmonetization', name: 'Line Item', def: 'The instruction in GAM telling the system who can show an ad, at what price, when, and where. Contains priority, targeting rules, creative assignments, and pacing settings.', related: ['gam','ad-unit','order','pg','publisher-ad-server'] },
  { id: 'order', clusterId: 'pubmonetization', name: 'Order', def: 'A container in GAM representing a relationship with a specific advertiser or agency. Holds all line items for that buyer.', related: ['line-item','gam','pg'] },
  { id: 'gpt', clusterId: 'pubmonetization', name: 'GPT', def: "Google Publisher Tag — the JavaScript code snippet placed on a site that communicates with GAM on every page load. Acts as the beacon that tells GAM a user arrived, then receives and renders the winning ad.", related: ['gam','ad-unit','header-bidding'] },
  { id: 'prebid-js', clusterId: 'pubmonetization', name: 'Prebid.js', def: 'Open-source JavaScript framework that manages the header bidding auction in the browser. Connects to dozens of SSPs simultaneously, enforces timeouts, collects bids, and passes the highest to GAM.', related: ['header-bidding','ssp','gam','prebid-timeout','waterfall'] },
  { id: 'prebid-timeout', clusterId: 'pubmonetization', name: 'Prebid Timeout', def: 'The maximum time Prebid.js waits for SSP bid responses. Best practice: 800–1200ms. Too long kills page load speed. Too short: low bid density and revenue loss.', related: ['prebid-js','header-bidding','fill-rate','lazy-loading'] },
  { id: 'lazy-loading', clusterId: 'pubmonetization', name: 'Lazy Loading', def: 'Triggering an ad call only when a user scrolls to within ~200 pixels of the slot. Dramatically improves viewability scores and reduces page weight.', related: ['viewability','prebid-timeout','ad-unit','fill-rate'] },
  { id: 'ad-refresh', clusterId: 'pubmonetization', name: 'Ad Refresh', def: 'Automatically replacing an ad in a slot and calling a new auction while the user stays on the page. Time-based or action-based. Golden rule: only refresh ads that are 100% in view.', related: ['viewability','fill-rate','ecpm','gam','lazy-loading'] },
  { id: 'floor-strategy', clusterId: 'pubmonetization', name: 'Floor Strategy', def: "Publisher's approach to setting minimum bid prices across inventory. Too high: low fill rate. Too low: leaving money on the table. Sophisticated floor strategies use dynamic pricing based on user signals and historical bid data.", related: ['floor-price','fill-rate','ecpm','header-bidding','win-rate'] },
  { id: 'rcpm', clusterId: 'pubmonetization', name: 'rCPM', def: "Revenue CPM — the publisher's actual earnings per 1,000 impressions. Different from eCPM in that it reflects take-home revenue after SSP fees. Formula: (Total Revenue ÷ Impressions) × 1,000.", related: ['ecpm','floor-strategy','ad-refresh','fill-rate'] },

  // 11 Performance
  { id: 'tofu-mofu-bofu', clusterId: 'performance', name: 'TOFU / MOFU / BOFU', def: 'Top / Middle / Bottom of Funnel. TOFU: awareness — make people know you exist. MOFU: consideration — turn curiosity into intent. BOFU: conversion — get the action. Different stages require different creatives, objectives, and measurement.', related: ['campaign-objective','retargeting-segments','creative-hook','cpa'] },
  { id: 'campaign-objective', clusterId: 'performance', name: 'Campaign Objective', def: 'The goal set at campaign level — what outcome the platform algorithm optimizes for. Wrong objective = the algorithm delivers exactly what you asked for, which is not what you wanted.', related: ['smart-bidding','tofu-mofu-bofu','cpa','roas'] },
  { id: 'cpa', clusterId: 'performance', name: 'CPA', def: 'Cost Per Action — what an advertiser pays per desired outcome: purchase, install, signup. The primary metric for conversion-focused campaigns. Formula: Total Spend ÷ Number of Conversions.', related: ['roas','smart-bidding','campaign-objective','cpc','horizontal-scaling'] },
  { id: 'roas', clusterId: 'performance', name: 'ROAS', def: 'Return on Ad Spend — revenue generated per dollar spent. Formula: Revenue ÷ Ad Spend. A ROAS of 4x means every $1 spent generates $4 in revenue. The primary profitability metric for ecommerce campaigns.', related: ['cpa','smart-bidding','data-driven-attribution','product-feed'] },
  { id: 'cpc', clusterId: 'performance', name: 'CPC', def: 'Cost Per Click — what an advertiser pays per click. Useful for traffic campaigns and early testing. Low CPC does not mean good performance: clicky users are not necessarily buying users.', related: ['cpa','ecpm','campaign-objective'] },
  { id: 'smart-bidding', clusterId: 'performance', name: 'Smart Bidding', def: 'Platform algorithm automatically adjusting bids in real time toward a defined conversion goal. Uses signals — device, time, behavior, location — to predict who is most likely to convert. Requires stable conversion data to work well.', related: ['learning-phase','cpa','roas','campaign-objective','data-driven-attribution'] },
  { id: 'learning-phase', clusterId: 'performance', name: 'Learning Phase', def: 'The period after a campaign launches when the algorithm collects enough conversion data to bid stably — typically 20–50 conversions per week. Editing the campaign resets it. Most campaign failures happen because learning never completes.', related: ['smart-bidding','cpa','campaign-objective'] },
  { id: 'retargeting-segments', clusterId: 'performance', name: 'Retargeting Segments', def: 'Distinct audience pools by purchase intent: View Content → Add to Cart → Checkout Initiated → Purchasers. Lumping all together dilutes performance. Each segment needs different creative and bid strategy.', related: ['tofu-mofu-bofu','dco','product-feed','cookie-sync','lookalike-audience'] },
  { id: 'lookalike-audience', clusterId: 'performance', name: 'Lookalike Audience', def: 'ML-generated audience of users who behave similarly to a seed group. Quality of the seed determines quality of the lookalike. Best seeds: actual purchasers. Worst seeds: all website visitors.', related: ['retargeting-segments','first-party-data','smart-bidding','horizontal-scaling'] },
  { id: 'horizontal-scaling', clusterId: 'performance', name: 'Horizontal Scaling', def: 'Growing a campaign by adding new surfaces — new audiences, creatives, geos, placements. The safer scaling method. Prevents audience burnout and CPA blowout.', related: ['cpa','roas','lookalike-audience','vertical-scaling'] },
  { id: 'vertical-scaling', clusterId: 'performance', name: 'Vertical Scaling', def: 'Increasing budget in an existing winning ad set. Simpler but riskier: increases frequency, can burn out audiences. Rule: increase budget by 20–30% at a time, once per day maximum.', related: ['horizontal-scaling','cpa','learning-phase'] },
  { id: 'creative-hook', clusterId: 'performance', name: 'Creative Hook', def: 'The first 3 seconds of an ad — the pattern interrupt that decides whether a user stops or scrolls. What works: bold claims, pain point callouts, physical interrupts. What kills CTR: slow pans, logos first, generic stock footage.', related: ['tofu-mofu-bofu','retargeting-segments','campaign-objective'] },

  // 12 Commercial
  { id: 'activate-audiences', clusterId: 'commercial', name: '"activate audiences"', def: 'Take your first-party customer data and use it to target ads across platforms. The standard verb in identity and data partnership conversations.', related: ['activation','first-party-data'] },
  { id: 'drive-revenue', clusterId: 'commercial', name: '"drive revenue"', def: 'Generate or grow income. Constant in commercial roles. Also useful in framing your own work: "I was responsible for driving DSP revenue on the demand side."', related: [] },
  { id: 'mutual-value', clusterId: 'commercial', name: '"mutual value"', def: 'What both sides get from a partnership. Use it to frame deals: "The mutual value here is incremental reach for you and improved fill for us."', related: [] },
  { id: 'strategic-alignment', clusterId: 'commercial', name: '"strategic alignment"', def: "When two companies' goals fit together cleanly. Used to frame why a partnership makes sense at a senior level.", related: [] },
  { id: 'pipeline', clusterId: 'commercial', name: '"pipeline"', def: "Deals in progress, not yet closed. 'What's in your pipeline?' is the standard question to a salesperson.", related: [] },
  { id: 'watch-this-space', clusterId: 'commercial', name: '"watch this space"', def: "Senior commercial register for 'this is going to develop further — stay tuned.' Used to signal competitive moves without specifics.", related: [] },
  { id: 'expand-relationship', clusterId: 'commercial', name: '"expand the relationship"', def: "Grow an existing partnership — more revenue, more integrations, more markets. Softer and more relational than 'upsell.'", related: [] },
  { id: 'incremental-reach', clusterId: 'commercial', name: '"incremental reach"', def: "New audience that wasn't being reached through existing channels. Key metric in partnership pitches.", related: [] },
];

export async function seedDatabase() {
  const batch = writeBatch(db);

  clusters.forEach(cluster => {
    const ref = doc(db, 'clusters', cluster.id);
    batch.set(ref, cluster);
  });

  terms.forEach(term => {
    const ref = doc(db, 'terms', term.id);
    batch.set(ref, term);
  });

  await batch.commit();
  console.log(`Seeded ${clusters.length} clusters and ${terms.length} terms.`);
}
